from typing import List
from ..schemas.travel import Place

INDIA_STATE_PLACES = [
    Place(
        id="andhra_tirumala",
        name="Tirumala Temple",
        description="A sacred hill shrine in Andhra Pradesh, visited for spiritual devotion and panoramic views.",
        lat=13.6836,
        lng=79.3496,
        categories=["history"],
        opening_hours={"open": 5.0, "close": 22.0},
        average_spend=200.0,
        duration_mins=120,
        walking_level="moderate",
        rating=4.8,
        user_ratings_total=44000,
        weather_suitability="both"
    ),
    Place(
        id="arunachal_tawang",
        name="Tawang Monastery",
        description="A revered Buddhist monastery in Arunachal Pradesh, known for its mountain setting and heritage.",
        lat=27.5868,
        lng=91.8656,
        categories=["history", "nature"],
        opening_hours={"open": 7.0, "close": 19.0},
        average_spend=180.0,
        duration_mins=90,
        walking_level="moderate",
        rating=4.7,
        user_ratings_total=18000,
        weather_suitability="outdoor"
    ),
    Place(
        id="assam_kaziranga",
        name="Kaziranga National Park",
        description="A UNESCO-listed wildlife sanctuary in Assam famous for rhinos, elephants, and birdlife.",
        lat=26.5775,
        lng=93.1711,
        categories=["nature"],
        opening_hours={"open": 7.0, "close": 16.0},
        average_spend=450.0,
        duration_mins=180,
        walking_level="moderate",
        rating=4.8,
        user_ratings_total=33000,
        weather_suitability="outdoor"
    ),
    Place(
        id="bihar_mahabodhi",
        name="Mahabodhi Temple",
        description="A sacred Buddhist temple in Bihar associated with the Buddha's enlightenment.",
        lat=24.6951,
        lng=84.9913,
        categories=["history"],
        opening_hours={"open": 5.0, "close": 21.0},
        average_spend=120.0,
        duration_mins=90,
        walking_level="moderate",
        rating=4.6,
        user_ratings_total=31000,
        weather_suitability="both"
    ),
    Place(
        id="chhattisgarh_chitrakote",
        name="Chitrakote Falls",
        description="A dramatic waterfall in Chhattisgarh, known for its wide cascade and natural scenery.",
        lat=19.0560,
        lng=81.8240,
        categories=["nature"],
        opening_hours={"open": 9.0, "close": 17.0},
        average_spend=100.0,
        duration_mins=120,
        walking_level="active",
        rating=4.4,
        user_ratings_total=16000,
        weather_suitability="outdoor"
    ),
    Place(
        id="goa_baga_beach",
        name="Baga Beach",
        description="A lively seaside destination in Goa with sand, nightlife, and seafood culture.",
        lat=15.5550,
        lng=73.7510,
        categories=["nature", "local food"],
        opening_hours={"open": 6.0, "close": 22.0},
        average_spend=350.0,
        duration_mins=120,
        walking_level="little",
        rating=4.4,
        user_ratings_total=56000,
        weather_suitability="outdoor"
    ),
    Place(
        id="gujarat_modhera",
        name="Modhera Sun Temple",
        description="A beautiful temple in Gujarat devoted to the Sun God and notable for elegant stonework.",
        lat=23.5877,
        lng=72.1330,
        categories=["history"],
        opening_hours={"open": 9.0, "close": 17.0},
        average_spend=120.0,
        duration_mins=75,
        walking_level="moderate",
        rating=4.5,
        user_ratings_total=17000,
        weather_suitability="outdoor"
    ),
    Place(
        id="haryana_surajkund",
        name="Surajkund Mela Grounds",
        description="A heritage destination in Haryana known for cultural fairs, crafts, and local traditions.",
        lat=28.5003,
        lng=77.1719,
        categories=["history", "local food"],
        opening_hours={"open": 9.0, "close": 18.0},
        average_spend=220.0,
        duration_mins=90,
        walking_level="moderate",
        rating=4.2,
        user_ratings_total=12000,
        weather_suitability="both"
    ),
    Place(
        id="himachal_shimla",
        name="Mall Road, Shimla",
        description="A classic hill-station promenade in Himachal Pradesh with colonial charm and mountain views.",
        lat=31.1048,
        lng=77.1734,
        categories=["nature", "history"],
        opening_hours={"open": 9.0, "close": 21.0},
        average_spend=260.0,
        duration_mins=90,
        walking_level="moderate",
        rating=4.5,
        user_ratings_total=28000,
        weather_suitability="outdoor"
    ),
    Place(
        id="jharkhand_hundru",
        name="Hundru Falls",
        description="A scenic waterfall in Jharkhand that offers dramatic views and a refreshing natural stop.",
        lat=23.4677,
        lng=85.6190,
        categories=["nature"],
        opening_hours={"open": 8.0, "close": 17.0},
        average_spend=100.0,
        duration_mins=90,
        walking_level="active",
        rating=4.3,
        user_ratings_total=15000,
        weather_suitability="outdoor"
    ),
    Place(
        id="karnataka_mysore",
        name="Mysore Palace",
        description="A grand royal palace in Karnataka famous for its architecture, heritage, and ceremonial splendor.",
        lat=12.3052,
        lng=76.6544,
        categories=["history"],
        opening_hours={"open": 10.0, "close": 17.5},
        average_spend=220.0,
        duration_mins=90,
        walking_level="moderate",
        rating=4.7,
        user_ratings_total=63000,
        weather_suitability="both"
    ),
    Place(
        id="kerala_munnar",
        name="Munnar Hills",
        description="A lush tea-garden hill station in Kerala with cool climate and sweeping valley views.",
        lat=10.0889,
        lng=77.0595,
        categories=["nature"],
        opening_hours={"open": 6.0, "close": 18.0},
        average_spend=300.0,
        duration_mins=120,
        walking_level="active",
        rating=4.7,
        user_ratings_total=49000,
        weather_suitability="outdoor"
    ),
    Place(
        id="munnar_tea_museum",
        name="Munnar Tea Museum",
        description="A heritage museum in Munnar that tells the story of tea culture, processing, and the region's colonial history.",
        lat=10.0863,
        lng=77.0647,
        categories=["history", "local food"],
        opening_hours={"open": 9.0, "close": 18.0},
        average_spend=180.0,
        duration_mins=90,
        walking_level="little",
        rating=4.5,
        user_ratings_total=18000,
        weather_suitability="both"
    ),
    Place(
        id="munnar_mattupetty_dam",
        name="Mattupetty Dam",
        description="A scenic reservoir in Munnar surrounded by rolling hills, lakes, and photo-friendly viewpoints.",
        lat=10.0900,
        lng=77.1185,
        categories=["nature"],
        opening_hours={"open": 9.0, "close": 17.0},
        average_spend=120.0,
        duration_mins=90,
        walking_level="moderate",
        rating=4.6,
        user_ratings_total=22000,
        weather_suitability="outdoor"
    ),
    Place(
        id="munnar_echo_point",
        name="Echo Point",
        description="A famous Munnar viewpoint where the valley echoes and the hills create a classic Kerala tea-country panorama.",
        lat=10.0959,
        lng=77.0836,
        categories=["nature"],
        opening_hours={"open": 8.0, "close": 18.0},
        average_spend=100.0,
        duration_mins=75,
        walking_level="little",
        rating=4.4,
        user_ratings_total=19000,
        weather_suitability="outdoor"
    ),
    Place(
        id="munnar_park",
        name="Eravikulam National Park",
        description="A protected high-altitude park in Munnar famous for the Nilgiri tahr and rolling grasslands.",
        lat=10.1263,
        lng=77.0551,
        categories=["nature", "history"],
        opening_hours={"open": 7.0, "close": 16.0},
        average_spend=220.0,
        duration_mins=120,
        walking_level="active",
        rating=4.8,
        user_ratings_total=34000,
        weather_suitability="outdoor"
    ),
    Place(
        id="munnar_kundala_lake",
        name="Kundala Lake",
        description="A calm lake nestled among tea gardens, ideal for relaxing walks, boating, and scenic views in Munnar.",
        lat=10.0990,
        lng=77.1036,
        categories=["nature", "local food"],
        opening_hours={"open": 9.0, "close": 17.0},
        average_spend=140.0,
        duration_mins=90,
        walking_level="little",
        rating=4.5,
        user_ratings_total=17000,
        weather_suitability="outdoor"
    ),
    Place(
        id="munnar_top_station",
        name="Top Station",
        description="A panoramic ridge viewpoint in Munnar offering dramatic tea-garden landscapes and cool mountain air.",
        lat=10.0750,
        lng=77.0055,
        categories=["nature"],
        opening_hours={"open": 8.0, "close": 16.0},
        average_spend=150.0,
        duration_mins=90,
        walking_level="moderate",
        rating=4.7,
        user_ratings_total=25000,
        weather_suitability="outdoor"
    ),
    Place(
        id="vagamon_meadows",
        name="Vagamon Meadows",
        description="A breezy, green plateau in Kerala known for misty slopes, open meadows, and calm nature walks.",
        lat=9.6395,
        lng=76.8871,
        categories=["nature"],
        opening_hours={"open": 6.0, "close": 18.0},
        average_spend=120.0,
        duration_mins=90,
        walking_level="moderate",
        rating=4.5,
        user_ratings_total=14000,
        weather_suitability="outdoor"
    ),
    Place(
        id="ooty_botanical_gardens",
        name="Government Botanical Garden",
        description="A famous Ooty garden with flower beds, viewpoint trails, and a laid-back hill station atmosphere.",
        lat=11.4100,
        lng=76.7135,
        categories=["nature"],
        opening_hours={"open": 8.0, "close": 18.0},
        average_spend=160.0,
        duration_mins=90,
        walking_level="moderate",
        rating=4.6,
        user_ratings_total=21000,
        weather_suitability="outdoor"
    ),
    Place(
        id="kodaikanal_lake",
        name="Kodaikanal Lake",
        description="A scenic lake in Tamil Nadu with promenade walks, boat rides, and a peaceful mountain setting.",
        lat=10.2381,
        lng=77.4892,
        categories=["nature", "local food"],
        opening_hours={"open": 6.0, "close": 18.0},
        average_spend=180.0,
        duration_mins=90,
        walking_level="little",
        rating=4.6,
        user_ratings_total=24000,
        weather_suitability="outdoor"
    ),
    Place(
        id="madhya_khajuraho",
        name="Khajuraho Temples",
        description="A stunning heritage site in Madhya Pradesh famous for its intricately carved temple sculptures.",
        lat=24.8533,
        lng=79.9220,
        categories=["history"],
        opening_hours={"open": 8.0, "close": 17.5},
        average_spend=180.0,
        duration_mins=120,
        walking_level="moderate",
        rating=4.6,
        user_ratings_total=26000,
        weather_suitability="outdoor"
    ),
    Place(
        id="maharashtra_gateway",
        name="Gateway of India",
        description="An iconic monument in Maharashtra overlooking the Arabian Sea and the city skyline.",
        lat=18.9220,
        lng=72.8347,
        categories=["history", "nature"],
        opening_hours={"open": 9.0, "close": 20.0},
        average_spend=180.0,
        duration_mins=75,
        walking_level="little",
        rating=4.6,
        user_ratings_total=74000,
        weather_suitability="both"
    ),
    Place(
        id="manipur_loktak",
        name="Loktak Lake",
        description="A large freshwater lake in Manipur known for floating phumdis and scenic landscapes.",
        lat=24.5178,
        lng=93.8133,
        categories=["nature"],
        opening_hours={"open": 6.0, "close": 18.0},
        average_spend=130.0,
        duration_mins=120,
        walking_level="little",
        rating=4.5,
        user_ratings_total=9000,
        weather_suitability="outdoor"
    ),
    Place(
        id="meghalaya_shillong",
        name="Shillong Viewpoint",
        description="A scenic lookout in Meghalaya with cool mountain air, green slopes, and charming city views.",
        lat=25.5788,
        lng=91.8933,
        categories=["nature"],
        opening_hours={"open": 7.0, "close": 19.0},
        average_spend=140.0,
        duration_mins=90,
        walking_level="little",
        rating=4.4,
        user_ratings_total=12000,
        weather_suitability="outdoor"
    ),
    Place(
        id="mizoram_reiek",
        name="Reiek Heritage Village",
        description="A culturally rich site in Mizoram offering tribal heritage and scenic mountain views.",
        lat=23.6889,
        lng=92.6455,
        categories=["history", "nature"],
        opening_hours={"open": 9.0, "close": 17.0},
        average_spend=160.0,
        duration_mins=90,
        walking_level="moderate",
        rating=4.3,
        user_ratings_total=8000,
        weather_suitability="both"
    ),
    Place(
        id="nagaland_kohima",
        name="Kohima War Cemetery",
        description="A moving historical memorial in Nagaland honoring soldiers of the Second World War.",
        lat=25.6747,
        lng=94.1077,
        categories=["history"],
        opening_hours={"open": 9.0, "close": 17.0},
        average_spend=100.0,
        duration_mins=60,
        walking_level="little",
        rating=4.6,
        user_ratings_total=11000,
        weather_suitability="outdoor"
    ),
    Place(
        id="odisha_konark",
        name="Konark Sun Temple",
        description="An ancient Sun temple in Odisha designed as a colossal chariot, admired for its stone sculpture.",
        lat=19.8876,
        lng=86.0943,
        categories=["history"],
        opening_hours={"open": 6.0, "close": 18.0},
        average_spend=120.0,
        duration_mins=90,
        walking_level="moderate",
        rating=4.6,
        user_ratings_total=26000,
        weather_suitability="outdoor"
    ),
    Place(
        id="punjab_goldentemple",
        name="Golden Temple",
        description="The spiritual heart of Amritsar in Punjab, celebrated for its architecture and community langar.",
        lat=31.6200,
        lng=74.8765,
        categories=["history"],
        opening_hours={"open": 24.0, "close": 24.0},
        average_spend=0.0,
        duration_mins=90,
        walking_level="moderate",
        rating=4.9,
        user_ratings_total=99000,
        weather_suitability="both"
    ),
    Place(
        id="rajasthan_amber",
        name="Amber Fort",
        description="A majestic hilltop fort in Rajasthan blending Rajput grandeur and scenic surroundings.",
        lat=26.9855,
        lng=75.8513,
        categories=["history"],
        opening_hours={"open": 9.0, "close": 17.5},
        average_spend=200.0,
        duration_mins=90,
        walking_level="moderate",
        rating=4.6,
        user_ratings_total=68000,
        weather_suitability="outdoor"
    ),
    Place(
        id="sikkim_tsomgo",
        name="Tsomgo Lake",
        description="A high-altitude lake in Sikkim, surrounded by snow peaks and alpine scenery.",
        lat=27.3671,
        lng=88.8041,
        categories=["nature"],
        opening_hours={"open": 8.0, "close": 17.0},
        average_spend=180.0,
        duration_mins=120,
        walking_level="moderate",
        rating=4.6,
        user_ratings_total=21000,
        weather_suitability="outdoor"
    ),
    Place(
        id="tamilnadu_meenakshi",
        name="Meenakshi Temple",
        description="A richly carved temple in Tamil Nadu attracting devotees and heritage travelers alike.",
        lat=9.9191,
        lng=78.1198,
        categories=["history"],
        opening_hours={"open": 5.0, "close": 21.0},
        average_spend=150.0,
        duration_mins=90,
        walking_level="moderate",
        rating=4.7,
        user_ratings_total=50000,
        weather_suitability="both"
    ),
    Place(
        id="telangana_charminar",
        name="Charminar",
        description="A historic monument in Telangana, known for its arches, bazaars, and old-city charm.",
        lat=17.3616,
        lng=78.4747,
        categories=["history"],
        opening_hours={"open": 9.0, "close": 17.0},
        average_spend=120.0,
        duration_mins=60,
        walking_level="little",
        rating=4.4,
        user_ratings_total=43000,
        weather_suitability="outdoor"
    ),
    Place(
        id="tripura_ujjayanta",
        name="Ujjayanta Palace",
        description="A heritage palace in Tripura reflecting local royal architecture and cultural history.",
        lat=23.8294,
        lng=91.2868,
        categories=["history"],
        opening_hours={"open": 10.0, "close": 17.0},
        average_spend=130.0,
        duration_mins=60,
        walking_level="little",
        rating=4.3,
        user_ratings_total=10000,
        weather_suitability="outdoor"
    ),
    Place(
        id="uttar_tajmahal",
        name="Taj Mahal",
        description="A marble mausoleum in Uttar Pradesh, celebrated around the world for love, craft, and symmetry.",
        lat=27.1751,
        lng=78.0421,
        categories=["history"],
        opening_hours={"open": 6.0, "close": 19.0},
        average_spend=250.0,
        duration_mins=120,
        walking_level="moderate",
        rating=4.8,
        user_ratings_total=120000,
        weather_suitability="outdoor"
    ),
    Place(
        id="uttarakhand_nainital",
        name="Nainital Lake",
        description="A scenic Himalayan lake in Uttarakhand known for boating, mountains, and relaxed walks.",
        lat=29.3800,
        lng=79.4540,
        categories=["nature"],
        opening_hours={"open": 6.0, "close": 20.0},
        average_spend=200.0,
        duration_mins=90,
        walking_level="little",
        rating=4.6,
        user_ratings_total=26000,
        weather_suitability="outdoor"
    ),
    Place(
        id="westbengal_darjeeling",
        name="Darjeeling Himalayan Railway",
        description="A heritage railway in West Bengal with scenic mountain routes and tea-garden landscapes.",
        lat=27.0371,
        lng=88.2627,
        categories=["history", "nature"],
        opening_hours={"open": 8.0, "close": 17.0},
        average_spend=180.0,
        duration_mins=90,
        walking_level="little",
        rating=4.5,
        user_ratings_total=21000,
        weather_suitability="both"
    ),
    Place(
        id="delhi_indiagate",
        name="India Gate",
        description="A war memorial in Delhi standing as a major historical landmark in the capital.",
        lat=28.6129,
        lng=77.2295,
        categories=["history"],
        opening_hours={"open": 9.0, "close": 21.0},
        average_spend=150.0,
        duration_mins=60,
        walking_level="little",
        rating=4.7,
        user_ratings_total=48000,
        weather_suitability="outdoor"
    ),
    Place(
        id="jammukashmir_dal",
        name="Dal Lake",
        description="A serene lake in Jammu & Kashmir beloved for shikaras, gardens, and mountain vistas.",
        lat=34.0837,
        lng=74.7973,
        categories=["nature"],
        opening_hours={"open": 6.0, "close": 20.0},
        average_spend=250.0,
        duration_mins=120,
        walking_level="little",
        rating=4.6,
        user_ratings_total=44000,
        weather_suitability="outdoor"
    ),
    Place(
        id="ladakh_pangong",
        name="Pangong Tso",
        description="A breathtaking high-altitude lake in Ladakh, famed for surreal blue waters and stark mountains.",
        lat=33.7629,
        lng=78.7155,
        categories=["nature"],
        opening_hours={"open": 7.0, "close": 18.0},
        average_spend=220.0,
        duration_mins=120,
        walking_level="moderate",
        rating=4.8,
        user_ratings_total=24000,
        weather_suitability="outdoor"
    ),
    Place(
        id="puducherry_beach",
        name="Promenade Beach",
        description="A scenic beach in Puducherry known for the French quarter, seaside walks, and sunsets.",
        lat=11.9364,
        lng=79.8304,
        categories=["nature"],
        opening_hours={"open": 6.0, "close": 21.0},
        average_spend=180.0,
        duration_mins=90,
        walking_level="little",
        rating=4.3,
        user_ratings_total=18000,
        weather_suitability="outdoor"
    ),
    Place(
        id="chandigarh_capitol",
        name="Capitol Complex",
        description="A modernist urban landmark in Chandigarh with architecture and landscaped public spaces.",
        lat=30.7522,
        lng=76.8066,
        categories=["history"],
        opening_hours={"open": 9.0, "close": 17.0},
        average_spend=80.0,
        duration_mins=60,
        walking_level="little",
        rating=4.4,
        user_ratings_total=7000,
        weather_suitability="both"
    ),
    Place(
        id="daman_diu_fort",
        name="Diu Fort",
        description="A Portuguese-era fort in Daman & Diu offering views over the Arabian Sea and a historic atmosphere.",
        lat=20.7186,
        lng=70.9990,
        categories=["history", "nature"],
        opening_hours={"open": 9.0, "close": 17.0},
        average_spend=110.0,
        duration_mins=75,
        walking_level="moderate",
        rating=4.3,
        user_ratings_total=7000,
        weather_suitability="both"
    ),
    Place(
        id="lakshadweep_agatti",
        name="Agatti Island Beach",
        description="A postcard-perfect island in Lakshadweep with turquoise waters and a quiet tropical setting.",
        lat=10.8537,
        lng=72.1918,
        categories=["nature"],
        opening_hours={"open": 6.0, "close": 18.0},
        average_spend=260.0,
        duration_mins=120,
        walking_level="little",
        rating=4.7,
        user_ratings_total=9000,
        weather_suitability="outdoor"
    ),
    Place(
        id="andaman_cellular",
        name="Cellular Jail",
        description="A historic colonial prison in Andaman & Nicobar Islands, embodying India's freedom struggle story.",
        lat=11.6760,
        lng=92.7402,
        categories=["history"],
        opening_hours={"open": 9.0, "close": 17.0},
        average_spend=120.0,
        duration_mins=90,
        walking_level="moderate",
        rating=4.5,
        user_ratings_total=19000,
        weather_suitability="both"
    )
]


def get_places() -> List[Place]:
    return INDIA_STATE_PLACES
